name: Opened issue details output workflow
on:
  issues:
    types: [opened]
jobs:
  event_info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo '${{toJson(github.event)}}'
